version: '3.4'

services:
  getcryptosimple:
    image: hendoapps.azurecr.io/getcryptosimple
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:3000
